## 산불 위험 정보
## 뒤늦게 데이터를 수집하기 시작햇기에 다른 가뭄영향지표분야보다 데이터 수가 적음

## 데이터 기간: 2025.09.02 08:00:00 ~ 현재까지
## 연, 월, 일: year의 입력 형태는 YYYY, month의 입력 형태는 MM, day의 입력 형태는 DD
## 특이사항: 연, 월, 일만 입력하면 시스템 내부적으로 현재 시간대를 산정하여 현재시간으로부터 가까운 시간대의 3일치 산불위험예보 데이터를 전달한다.
### [GET] 산불 위험 지수 예보 (3일치)
GET http://localhost:8080/api/v1/wild-fire-risk/forecast?year=2026&month=04&day=20

## 데이터 기간: 2025.09.02 ~ 2025.12.31
## 연, 월, 일: year의 입력 형태는 YYYY, month의 입력 형태는 MM, day의 입력 형태는 DD
## 특이사항: 가뭄과 관련된 뉴스가 없는 경우 수집을 안할 수 도 있으며 연관성이 없는 뉴스가 수집될 수 있다.
### [GET] 산불 관련 뉴스 기사
GET http://localhost:8080/api/v1/wild-fire-risk/news-article?year=2025&month=12
